In [69]:
import pandas as pd

In [70]:
pd.options.display.max_rows = 1000
pd.options.display.max_columns = 13

In [71]:
data = pd.read_csv("Titanic-Dataset.csv")

<h4><b>Informations about the dataset</b></h4>

<ul>
    <li>Passenger ID</li>
    <li>Survived: 0 = No     1 = Yes</li>
    <li>Pclass: Ticket classe 1= 1st class, 2= 2nd class, 3= 3rd class </li>
    <li>Name: of passenger 891 unique values</li>
    <li>Sex: male 65% or female 35%</li>
    <li>Age: in years</li>
    <li>SibSp: Number of siblings/spouses abroad the titanic</li>
    <li>Parch: Number of parents/children abroad the titanic</li>
    <li>Ticket: Ticket number </li>
    <li>Fare: Passenger fare the price the passenger payd to travel on titanic</li>
    <li>Cabin: Cabin number</li>
    <li>Embarked: Port of Embarkation:C = Cherbourg, Q = Queenstown, S = Southampton</li>

</ul>

In [72]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [73]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [74]:
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

### Column 'Survived'

In [75]:
# Column 'Survived'
# Making sure the only values are 0 and 1

print(data['Survived'].unique())

[0 1]

### Column 'Pclass'

In [76]:
# Column 'Pclass'
# Making sure the only values are 1, 2 and 3

print(data['Pclass'].unique())

[3 1 2]

### Column 'Sex'

In [77]:
# Column 'Sex'
# Making sure the only values are female and male

print(data['Sex'].unique())

['male' 'female']

### Column 'Age'

In [78]:
# correct age values
for i in data['Age']:
    if i<1:
        print(i)

0.83
0.92
0.75
0.75
0.67
0.42
0.83

In [79]:
# Those values represents the age of infants <1 year
# DO NOT CHANGE IT !!!!

### Null values

In [80]:
print(data.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [82]:
# Clean age columns
data['Age'].fillna(data['Age'].median(), inplace= True)
print(data.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [85]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

### Duplicated values

In [86]:
data.duplicated().sum()

0