<h1><center> Adult Income Dataset (UCI machine learning repository)

<h2> III)- Feature Engineering

In [116]:
import numpy as np 
import pandas as pd

In [117]:
adult = pd.read_csv('C:\\Users\\hp\\Desktop\\100 Days of data science practise\\Day25 complete Project\\Data cleaning\\clean_data.csv')
adult.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [118]:
adult.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

### 1)- la colonne 'age'

In [119]:
adult['age'].min(), adult['age'].max()

(17, 90)

### 2)- la colonne 'workclass'

In [120]:
adult['workclass'].value_counts()

Private             33281
Self-emp-not-inc     3795
Local-gov            3100
State-gov            1946
Self-emp-inc         1645
Federal-gov          1406
Without-pay            21
Name: workclass, dtype: int64

### 3)- la colonne 'fnlwgt'

In [121]:
adult['fnlwgt'].value_counts()

203488    21
120277    18
125892    18
126569    17
113364    17
          ..
49837      1
345363     1
162856     1
278938     1
350977     1
Name: fnlwgt, Length: 26741, dtype: int64

In [122]:
# On supprime cette colonne
adult.drop(columns=['fnlwgt'], inplace=True)
adult.head(3)

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K

La colonne 'fnlwgt' est une variable de pondération statistique, elle n'est pas utile pour un projet machine learning!

### 4)- les colonne 'education' et 'education-num'

In [123]:
print(adult['education'].value_counts())
print(adult['education-num'].value_counts())

HS-grad         14777
Some-college     9890
Bachelors        7565
Masters          2513
Assoc-voc        1958
11th             1619
Assoc-acdm       1507
10th             1223
7th-8th           822
Prof-school       785
9th               676
12th              576
Doctorate         544
5th-6th           448
1st-4th           220
Preschool          71
Name: education, dtype: int64
9     14777
10     9890
13     7565
14     2513
11     1958
7      1619
12     1507
6      1223
4       822
15      785
5       676
8       576
16      544
3       448
2       220
1        71
Name: education-num, dtype: int64

HS-grad = 9       14777

Some-college = 10     9890

Bachelors = 13      7565

Masters = 14        2513

Assoc-voc = 11       1958

11th = 7            1619

Assoc-acdm = 12       1507

10th = 6             1223

7th-8th = 4          822

Prof-school = 15       785

9th = 5               676

12th = 8              576

Doctorate = 16        544

5th-6th = 3           448

1st-4th = 2           220

Preschool = 1         71

In [124]:
# On supprime la colonne 'education' et on garde juste la colonne 'education-num'
adult.drop(columns=['education'], inplace= True)
adult.head(2)

,age,workclass,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K

### 5)- la colonne 'sex'

In [125]:
adult['sex'].value_counts()

Male      30509
Female    14685
Name: sex, dtype: int64

In [126]:
# Pour cette colonne on remplace male par 1 et female par 0
adult['sex'] = adult['sex'].replace({
                                        'Male': 1,
                                        'Female': 0
})
adult['sex'].value_counts()

1    30509
0    14685
Name: sex, dtype: int64

### 6)- Les colonnes 'capital-gain', 'capital-loss', 'hours-per-week'

In [127]:
# Rien à changer
print(adult['capital-gain'].min(), adult['capital-gain'].max())
print("\n", adult['capital-loss'].min(), adult['capital-loss'].max())
print("\n", adult['hours-per-week'].min(), adult['hours-per-week'].max())

0 99999

 0 4356

 1 99

In [128]:
adult['hours-per-week'].describe()

count    45194.000000
mean        40.941209
std         12.006449
min          1.000000
25%         40.000000
50%         40.000000
75%         45.000000
max         99.000000
Name: hours-per-week, dtype: float64

In [129]:
adult['capital-gain'].value_counts().head(10) 
# On a beaucoup de valeur avec 0, c'est une variable déséquilibrée

0        41404
15024      498
7688       391
7298       351
99999      229
3103       146
5178       137
5013       116
4386       102
3325        81
Name: capital-gain, dtype: int64

In [130]:
adult['capital-loss'].value_counts().head(10) 
# On a beaucoup de valeur avec 0, c'est une variable déséquilibrée

0       43054
1902      294
1977      246
1887      228
2415       68
1848       65
1485       65
1876       59
1590       58
1740       57
Name: capital-loss, dtype: int64

<b> On doit transformer les colonnes 'capital-gain' et 'capital-loss'


### 6)- La colonne 'occupation',

In [131]:
adult['occupation'].value_counts()

Craft-repair         6015
Prof-specialty       6003
Exec-managerial      5982
Adm-clerical         5537
Sales                5408
Other-service        4805
Machine-op-inspct    2967
Transport-moving     2316
Handlers-cleaners    2045
Farming-fishing      1477
Tech-support         1419
Protective-serv       976
Priv-house-serv       230
Armed-Forces           14
Name: occupation, dtype: int64

In [132]:
# On va suprimer ma colonne 'occupation'
adult.drop(columns=['occupation'], inplace= True)
adult.head(2)

,age,workclass,education-num,marital-status,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,13,Never-married,Not-in-family,White,1,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,13,Married-civ-spouse,Husband,White,1,0,0,13,United-States,<=50K

### 7)- Les colonnes 'marital-status', 'relationship'

In [133]:
adult['marital-status'].value_counts()

Married-civ-spouse       21048
Never-married            14580
Divorced                  6294
Separated                 1411
Widowed                   1277
Married-spouse-absent      552
Married-AF-spouse           32
Name: marital-status, dtype: int64

In [134]:
adult['relationship'].value_counts()

Husband           18659
Not-in-family     11687
Own-child          6621
Unmarried          4787
Wife               2091
Other-relative     1349
Name: relationship, dtype: int64

In [135]:
# On va supprimer la colonne 'relationship' 
adult.drop(columns=['relationship'], inplace= True)
adult.head(1)

,age,workclass,education-num,marital-status,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,13,Never-married,White,1,2174,0,40,United-States,<=50K

In [136]:
# Pour la colonne 'marital-status' on va remplacé par deux valeurs seulement marrié ou non 
# marrié : 1 non marrié : 0
adult['married'] = adult['marital-status'].replace({
                                                                'Married-civ-spouse': 1 ,
                                                                'Never-married' : 0 ,          
                                                                'Divorced' : 0  ,                
                                                                'Separated' : 0  ,             
                                                                'Widowed' : 0 ,                  
                                                                'Married-spouse-absent' : 1 ,      
                                                                'Married-AF-spouse' : 1          
})
adult.head(2)

,age,workclass,education-num,marital-status,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income,married
0,39,State-gov,13,Never-married,White,1,2174,0,40,United-States,<=50K,0
1,50,Self-emp-not-inc,13,Married-civ-spouse,White,1,0,0,13,United-States,<=50K,1

In [137]:
# On supprime maintenant la colonne 'marital-status'

adult.drop(columns= ['marital-status'], inplace= True)
adult.head(2)

,age,workclass,education-num,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income,married
0,39,State-gov,13,White,1,2174,0,40,United-States,<=50K,0
1,50,Self-emp-not-inc,13,White,1,0,0,13,United-States,<=50K,1

### 8)- Les colonnes 'race', 'native-country',

In [138]:
adult['race'].value_counts()

White                 38877
Black                  4227
Asian-Pac-Islander     1302
Amer-Indian-Eskimo      435
Other                   353
Name: race, dtype: int64

In [139]:
adult['native-country'].value_counts()

United-States         41292
Mexico                  899
Philippines             283
Germany                 193
Puerto-Rico             175
Canada                  163
El-Salvador             147
India                   147
China                   141
Cuba                    133
England                 119
Jamaica                 103
South                   101
Italy                   100
Dominican-Republic       97
Japan                    89
Guatemala                84
Vietnam                  83
Columbia                 82
Poland                   81
Haiti                    69
Portugal                 62
Iran                     56
Taiwan                   55
Greece                   49
Nicaragua                48
Peru                     45
Ecuador                  43
France                   36
Ireland                  36
Thailand                 29
Cambodia                 26
Trinadad & Tobago        26
Yugoslavia               23
Laos                     21
Scotland                 20
Honduras                 19
Hungary                  18
Holand-Netherlands        1
Name: native-country, dtype: int64

In [140]:
# On supprime la colonne 'native-country'
adult.drop(columns= ['native-country'], inplace= True)
adult.head(2)

,age,workclass,education-num,race,sex,capital-gain,capital-loss,hours-per-week,income,married
0,39,State-gov,13,White,1,2174,0,40,<=50K,0
1,50,Self-emp-not-inc,13,White,1,0,0,13,<=50K,1

### 9)- La colonne 'income'

In [141]:
adult['income'].value_counts()

<=50K    33988
>50K     11206
Name: income, dtype: int64

In [142]:
# On va convertir la colonne 'income' en int
adult['income'] = adult['income'].replace({
                                                                '<=50K': 0 ,
                                                                '>50K' : 1          
})
adult.head(2)

,age,workclass,education-num,race,sex,capital-gain,capital-loss,hours-per-week,income,married
0,39,State-gov,13,White,1,2174,0,40,0,0
1,50,Self-emp-not-inc,13,White,1,0,0,13,0,1

In [145]:
# Pour le reste des colonnes 'workclass' 'race' on va faire le one hot encoding

adult = pd.get_dummies(adult, columns=['race', 'workclass'], drop_first= True)
adult.head()

,age,education-num,sex,capital-gain,capital-loss,hours-per-week,income,married,race_Asian-Pac-Islander,race_Black,race_Other,race_White,workclass_Local-gov,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Without-pay
0,39,13,1,2174,0,40,0,0,0,0,0,1,0,0,0,0,1,0
1,50,13,1,0,0,13,0,1,0,0,0,1,0,0,0,1,0,0
2,38,9,1,0,0,40,0,0,0,0,0,1,0,1,0,0,0,0
3,53,7,1,0,0,40,0,1,0,1,0,0,0,1,0,0,0,0
4,28,13,0,0,0,40,0,1,0,1,0,0,0,1,0,0,0,0

In [146]:
adult.to_csv('C:\\Users\\hp\\Desktop\\100 Days of data science practise\\Day25 complete Project\\Feature Engineering\\Data-engineering.csv', header= True, index= False)
print("le fichier a été enregistré avec succés !")

le fichier a été enregistré avec succés !